//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Pyroscope.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeProfileTarget) DeepCopyInto(out *PyroscopeProfileTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeProfileTarget.
func (in *PyroscopeProfileTarget) DeepCopy() *PyroscopeProfileTarget {
	if in == nil {
		return nil
	}
	out := new(PyroscopeProfileTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PyroscopeProfileTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeProfileTargetList) DeepCopyInto(out *PyroscopeProfileTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PyroscopeProfileTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeProfileTargetList.
func (in *PyroscopeProfileTargetList) DeepCopy() *PyroscopeProfileTargetList {
	if in == nil {
		return nil
	}
	out := new(PyroscopeProfileTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PyroscopeProfileTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeProfileTargetSpec) DeepCopyInto(out *PyroscopeProfileTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeProfileTargetSpec.
func (in *PyroscopeProfileTargetSpec) DeepCopy() *PyroscopeProfileTargetSpec {
	if in == nil {
		return nil
	}
	out := new(PyroscopeProfileTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeProfileTargetStatus) DeepCopyInto(out *PyroscopeProfileTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeProfileTargetStatus.
func (in *PyroscopeProfileTargetStatus) DeepCopy() *PyroscopeProfileTargetStatus {
	if in == nil {
		return nil
	}
	out := new(PyroscopeProfileTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeServer) DeepCopyInto(out *PyroscopeServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeServer.
func (in *PyroscopeServer) DeepCopy() *PyroscopeServer {
	if in == nil {
		return nil
	}
	out := new(PyroscopeServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PyroscopeServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeServerList) DeepCopyInto(out *PyroscopeServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PyroscopeServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeServerList.
func (in *PyroscopeServerList) DeepCopy() *PyroscopeServerList {
	if in == nil {
		return nil
	}
	out := new(PyroscopeServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PyroscopeServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeServerSpec) DeepCopyInto(out *PyroscopeServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeServerSpec.
func (in *PyroscopeServerSpec) DeepCopy() *PyroscopeServerSpec {
	if in == nil {
		return nil
	}
	out := new(PyroscopeServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PyroscopeServerStatus) DeepCopyInto(out *PyroscopeServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PyroscopeServerStatus.
func (in *PyroscopeServerStatus) DeepCopy() *PyroscopeServerStatus {
	if in == nil {
		return nil
	}
	out := new(PyroscopeServerStatus)
	in.DeepCopyInto(out)
	return out
}
