# permissions for end users to view pyroscopeprofiletargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pyroscopeprofiletarget-viewer-role
rules:
- apiGroups:
  - operator.pyroscope.io
  resources:
  - pyroscopeprofiletargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.pyroscope.io
  resources:
  - pyroscopeprofiletargets/status
  verbs:
  - get
