# permissions for end users to edit pyroscopeprofiletargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pyroscopeprofiletarget-editor-role
rules:
- apiGroups:
  - operator.pyroscope.io
  resources:
  - pyroscopeprofiletargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.pyroscope.io
  resources:
  - pyroscopeprofiletargets/status
  verbs:
  - get
